intelliShare/routes.py
from datetime import datetime
from flask import abort, jsonify, request, render_template, redirect, session, url_for, Blueprint, flash, send_from_directory
from flask_login import login_user, login_required, logout_user
import os
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc
from werkzeug.security import generate_password_hash, check_password_hash
from .models import Question, User, Answer
from .db import db

main = Blueprint("main", __name__)

# Temporary data storage
questions = []
answers = []

# Configure upload folder and allowed extensions
PROJ='intelliShare'
UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

# Ensure the upload directory exists
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
# Check if the uploaded file is allowed
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@main.route('/')
def home():
    posts = get_posts_from_database(0, 2)
    return render_template('index.html', posts=posts)

class Post:
    def __init__(self, question_id, question, username, timestamp, content):
        self.question_id = question_id
        self.question = question
        self.username = username
        self.timestamp = timestamp
        self.content = content

        def to_dict(self):
            return {
                'id': self.id,
                'title': self.title,
                'content': self.content,
            }

# Function to get posts from the database
def get_posts_from_database(start, limit):
    all_posts = Question.query.order_by(desc(Question.post_time)).all()  # get all posts ordered by timestamp
    return all_posts[start:start+limit]


@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        r = request.get_json()
        username = r['username']
        password = r['password']

        user = User.query.filter_by(username=username).first()
        if user and user.password == password:
            login_user(user)
            session['username'] = user.username  # Set the session
            return {"status": 200, "message": "success", "username": user.username}
        return {"status": 400, "message": "Wrong Combination, Try again!"}
    return render_template('index.html')

@main.route('/check_login')
def check_login():
    if 'username' in session:
        return jsonify({'status': 200, 'username': session['username']})
    return jsonify({'status': 401})


# create new question
@main.route('/addQuestion_v1', methods=['GET', 'POST'])
def add_question():
    if request.method == 'POST':
        title = request.form['title']
        subtitle = request.form['subtitle']
        question_text = request.form['question']
        user_id = 'user_id'
        username = 'username'
        submission_time = datetime.now().strftime('%d %b %Y %H:%M:%S')
        
        filename = None
        if 'cover' in request.files:
            file = request.files['cover']
            if file and allowed_file(file.filename):
                filename = file.filename
                filepath = os.path.join(PROJ, UPLOAD_FOLDER, filename)
                file.save(filepath)

        question_id = len(questions) + 1
        questions.append({
            'id': question_id,
            'title': title,
            'subtitle': subtitle,
            'question': question_text,
            'cover': filename,
            'username': username,
            'submission_time': submission_time,
            'user_id': user_id
        })
        
        new_question = Question()

        new_question.title = title
        new_question.subtitle = subtitle
        new_question.content = question_text
        new_question.cover = filename
        new_question.post_time = submission_time  
        new_question.user_id = user_id
        new_question.username = username

        db.session.add(new_question)
        db.session.commit()

        return redirect(url_for('main.question_details', question_id=question_id))
    
    return render_template('addQuestion_v1.html')

#@main.route('/addQuestion_v1.html')
#def add():
#    return render_template('addQuestion_v1.html')

@main.route('/questionDetails_v1.html')
def details():
    return render_template('questionDetails_v1.html')

# Route to handle answer submissions
@main.route('/questionDetails_v1.html', methods=['GET','POST'])
def answer():
    question_id = int(request.form['question_id'])
    comment = request.form['answer']
    answer_time = datetime.now().strftime('%d %b %Y %H:%M:%S')
    user_id = 1
    print(question_id, comment, answer_time)
    new_answer = Answer()
    new_answer.question_id=question_id
    new_answer.comment=comment 
    new_answer.answer_time=answer_time 
    new_answer.user_id=user_id
        
    # Handle file upload
    if 'file' in request.files:
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = file.filename
            filepath = os.path.join(PROJ, UPLOAD_FOLDER, filename)
            file.save(filepath)
            new_answer.image = filename
    
    db.session.add(new_answer)
    db.session.commit()

    return redirect(url_for('main.question_details', question_id=question_id))

@main.route('/profile', methods=['GET', 'POST'])
def profile():
    return render_template('profile.html')

# Route to display question details and answers
@main.route('/questionDetails_v1.html/<int:question_id>')
def question_details(question_id):
    question = next((q for q in questions if q['id'] == question_id), None)
    if not question:
        return "Question not found", 404

    answers =  db.session.execute(db.select(Answer).filter_by(question_id=question_id)).all()
    a_unames = [ db.session.execute(db.select(User).filter_by(id=a[0].user_id)).scalar_one_or_none() for a in answers]
    a_unames = [ u.username for u in a_unames]
    a_time = [a[0].answer_time for a in answers]
    a_image = [a[0].image for a in answers]
    a_comment = [a[0].comment for a in answers]
    alist = []
    for i in range(len(a_time)):
        alist.append({
            "username":a_unames[i],
            "answer_time":a_time[i],
            "image":a_image[i],
            "comment": a_comment[i]
        })
    print(alist)
    return render_template('questionDetails_v1.html', question=question, answers=alist)

@main.route('/search', methods=['GET', 'POST'])
def search():
    query = request.args.get('query')
    results = []

    if query:  # only search if a query is provided
        all_posts = get_posts_from_database(0, 100)  # get all posts
        results = [post for post in all_posts if query in post.title]  # search in post question

        if not results:
            flash('No results found!')

    return render_template('search.html', results=results)

    # Serve uploaded files
@main.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory(UPLOAD_FOLDER, filename)

# Route to handle profile submission
@main.route('/submit_profile', methods=['POST'])
def submit_profile():
    try:
        username = request.form['username']
        password = request.form['password']

        if not username or not password:
            return jsonify({'message': 'Username and password are required!'}), 400

        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            return jsonify({'message': 'Username already exists!'}), 400

        image = None
        if 'image' in request.files:
            file = request.files['image']
            if file and allowed_file(file.filename):
                filename = file.filename
                file.save(os.path.join(UPLOAD_FOLDER, filename))
                image = filename
        else:
            image = 'default_image.jpg' 

        new_user = User(
            username=username,
            password=password,
            image=image
        )

        db.session.add(new_user)
        db.session.commit()

        return jsonify({'message': 'Profile submitted successfully!'})
    except Exception as e:
        return jsonify({'message': 'An error occurred', 'error': str(e)}), 500


@main.route('/get_more_posts', methods=['GET'])
def get_more_posts():
    start = request.args.get('start', type=int)
    limit = request.args.get('limit', type=int)
    more_questions = get_posts_from_database(start, limit)  # Assuming this function now returns Question objects
    return jsonify([question.to_dict() for question in more_questions])

@main.route('/questioninfo/<int:question_id>')
def question_details_copy(question_id):
    # Fetch the question from the database using question_id
    question = Question.query.get(question_id)
    if question is None:
        abort(404)  # Not found
    answers = db.session.query(
        Answer.id,
        Answer.comment,
        Answer.answer_time,
        Answer.user_id,
        Answer.question_id
    ).filter(
        Answer.question_id == question_id
    ).all()
    print(answers)  # Print the answers to the console
    return render_template('questioninfo.html', question=question, answers=answers)

@main.route('/logout')
def logout():
    session.pop('username', None)
    return render_template('index.html')

intelliShare/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IntelliShare</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../static/style.css">
</head>
<body>

   <!--  menu bar -->
   <div id="container">
    <span class="title">
        IntelliShare
    </span>
</div>
  
  <div class="menubar">
    <div class="element" id="home"><img src="{{ url_for('static', filename='home.png') }}" alt="home"><a href="{{ url_for('main.home') }}">Home</a></div>
    <div class="element" id="search"><img src="{{ url_for('static', filename='search.png') }}" alt="search"><a href="{{ url_for('main.search') }}">Search</a></div>
</div>

<!-- Content -->

<!-- select posts go here-->
<div class="content">
    <div class="contentpic"><img src="../static/intelliShare.png" alt="contentpic"></div>
    <span id="articletitle">IntelliShare: Connecting Questions and Answers Seamlessly</span>
</div>

<!-- post -->
<div class="question-container">

    {% for post in posts %}
    <div class="question">
        <h2><a href="{{ url_for('main.question_details_copy', question_id=post.id) }}">{{ post.title }}</a></h2>
        <hr>
        <span class="usericon"><img src="../static/usericon.png" alt=""></span>
        <span class="usernameComment">{{ post.username }}</span>
        <span class="lastreply">{{ post.timestamp }}</span>
            <p>{{ post.content }}</p>
    </div>

    {% endfor %}
    <!-- More button -->
    <div class="more-button-container">
        <button class="more-button" id="loadMore" >More</button>
    </div>
</div>

<!--  profile -->
<div class="profilemenu">
    <button id="authButton" type="button" class="button-profile" onclick="toggleAuth()">Sign up / Login</button>
    <button id="logoutButton" type="button" class="button-logout" onclick="logout()">Logout</button>
    <button id="addQuestion" type="button" class="button-addQuestion" onclick="location.href='{{ url_for('main.add_question') }}'">Add Question</button>
    <span class="userpic"><img src="../static/userpic.png" alt="userpic"></span>
    <span id="username" class="username"></span>

</div>

<!-- Login Modal -->
<div id="loginModal" class="login-modal">
    <h2>Login</h2>
    <input type="text" id="usernameInput" placeholder="Username"><br>
    <input type="password" id="passwordInput" placeholder="Password"><br>
    <button onclick="login()">Login</button>
    <button onclick="navigateToProfile()">Sign Up</button>
    <button onclick="closeModal()">Close</button>

</div>

<!-- Alert Modal -->
<div id="alertModal" class="alert-modal">
    <p id="alertMessage"></p>
</div>



<script src="{{ url_for('static', filename='scripts_home.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

intelliShare/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IntelliShare</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles_profile.css') }}">
</head>
<body>

<!-- menu bar -->
  <div class="title">
      IntelliShare
  </div>
  
  <div class="menubar">
    <div class="element" id="home"><img src="{{ url_for('static', filename='home.png') }}" alt="home"><a href="{{ url_for('main.home') }}">Home</a></div>
    <div class="element" id="search"><img src="{{ url_for('static', filename='search.png') }}" alt="search"><a href="{{ url_for('main.search') }}">Search</a></div>
  </div>

<!-- Content -->
<form id="profile" action="{{ url_for('main.submit_profile') }}" method="POST" enctype="multipart/form-data">
    <div class="userpic-container">
        <span class="userpic"><img src="{{ url_for('static', filename='userpic.png') }}" alt="userpic"></span>
    </div>

    <div class="form-content">
        <div class="profile-container">
            <label for="username">User Name</label>
            <input type="text" id="username" name="username" placeholder="momo" maxlength="50" required>
        </div>
        <div class="profile-container">
            <label for="gender">Gender</label>
            <select class="form-select" id="gender" name="gender" required>
                <option selected value="">Choose...</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="secret">Keep as A Secret</option>
            </select>
        </div>
        <div class="profile-container">
            <label for="occupation">Occupation</label>
            <select class="form-select" id="occupation" name="occupation" required>
                <option selected value="">Choose...</option>
                <option value="student">Student</option>
                <option value="teacher">Teacher</option>
                <option value="engineer">Engineer</option>
                <option value="doctor">Doctor</option>
                <option value="software_developer">Software Developer</option>
                <option value="nurse">Nurse</option>
                <option value="artist">Artist</option>
                <option value="sales_professional">Sales Professional</option>
                <option value="manager">Manager</option>
                <option value="consultant">Consultant</option>
                <option value="freelancer">Freelancer</option>
                <option value="entrepreneur">Entrepreneur</option>
                <option value="other">Other</option>
            </select>
        </div>
        <div class="profile-container">
            <label for="selfIntro">Self Introduction</label>
            <textarea id="selfIntro" name="selfIntro" placeholder="Just a curious explorer of the vast and exciting world!😊" maxlength="256" rows="3" required></textarea>
        </div>
        <div class="profile-container">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" required maxlength="20">
        </div>
        <div class="profile-container">
            <label for="securityQuestion">Security Question</label>
            <select class="form-select" id="securityQuestion" name="securityQuestion" required>
                <option selected value="">Choose...</option>
                <option value="maiden-name">Mother's Maiden Name</option>
                <option value="pet-name">Pet's Name</option>
                <option value="fav-place">Favourite Place</option>
                <option value="pob">Place of Birth</option>
                <option value="dob">Date of Birth</option>
                <option value="tob">Town of Birth</option>
                <option value="fav-color">Favourite Color</option>
            </select>
        </div>
        <div class="profile-container">
            <label for="securityAnswer">Security Answer</label>
            <input type="text" id="securityAnswer" name="securityAnswer" required maxlength="256">
        </div>
    </div>

    <div class="button-group">
        <button type="submit" id="submitBtn" class="button-submit">Submit</button>
        <button type="button" onclick="window.location.href='/'" class="button-cancel">Cancel</button>
    </div>
</form>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='scripts_profile.js') }}"></script>
</body>
</html>

intelliShare/templates/questionDetails_v1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Details</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles_questionDetails.css') }}">
</head>
<body>
    <div id="container">  
        <span class="title">IntelliShare</span>
    </div>
    <div class="menubar">
        <div class="element" id="home"><img src="{{ url_for('static', filename='home.png') }}" alt="home"><a href="{{ url_for('main.home') }}">Home</a></div>
        <div class="element" id="search"><img src="{{ url_for('static', filename='search.png') }}" alt="search"><a href="{{ url_for('main.search') }}">Search</a></div>
      </div>

    <!-- Content -->
    <div class="comment1">
        <div class="contentpic">
            <img src="{{ url_for('main.uploaded_file', filename=question.cover) }}" alt="Content Picture">
        </div>
        <span class="usericon"><img src="{{ url_for('static', filename='usericon.png') }}" alt=""></span>
        <span class="usernameComment">{{ question.username }}</span>
        <span class="lastreply">Posted at {{ question.submission_time }}</span>

        <span id="group">{{ question.title }}</span>    
        <span id="title">{{ question.subtitle }}</span> 
        <span id="summary">{{ question.question }}</span>
        <div class="answer1">
            <form action="/questionDetails_v1.html" method="post" enctype="multipart/form-data">
                <input type="hidden" name="question_id" value="{{ question.id }}">
                <input type="text" id="write" name="answer" placeholder="Write my answer">
                <input type="file" name="file" accept="image/*">
                <button type="submit" id="button-send">Send</button>
            </form>
        </div>
    </div>
    <!-- Display answers -->
    <div class="post2">
        {% for answer in answers %}
        <div class="answer-block">
            <span class="usernameAnswer2">{{ answer.username }}</span>
            <br><span class="lastAnswer2">Answered at {{ answer.answer_time }}</span>
            {% if answer.image %}
            <img src="{{ url_for('main.uploaded_file', filename=answer.image) }}" alt="Answer Image">
            {% endif %}
            <p>{{ answer.comment }}</p>
        </div>
        {% endfor %}
    </div>

    <!--  profile -->
<div class="profilemenu">
    <button id="authButton" type="button" class="button-profile" onclick="toggleAuth()">Sign up / Login</button>
    <button id="logoutButton" type="button" class="button-logout" onclick="logout()">Logout</button>
    <button id="addQuestion" type="button" class="button-addQuestion" onclick="location.href='{{ url_for('main.add_question') }}'">Add Question</button>
    <span class="userpic"><img src="../static/userpic.png" alt="userpic"></span>
    <span id="username" class="username"></span>

</div>

<!-- Login Modal -->
<div id="loginModal" class="login-modal">
    <h2>Login</h2>
    <input type="text" id="usernameInput" placeholder="Username"><br>
    <input type="password" id="passwordInput" placeholder="Password"><br>
    <button onclick="login()">Login</button>
    <button onclick="navigateToProfile()">Sign Up</button>
    <button onclick="closeModal()">Close</button>

</div>

<!-- Alert Modal -->
<div id="alertModal" class="alert-modal">
    <p id="alertMessage"></p>
</div>

<script src="{{ url_for('static', filename='scripts_qd.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

intelliShare/templates/questioninfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Details</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles_questionDetails.css') }}">
</head>
<body>
   <div id="container">  
        <span class="title">IntelliShare</span>
    </div>
    <div class="menubar">
        <div class="element" id="home"><img src="{{ url_for('static', filename='home.png') }}" alt="home"><a href="{{ url_for('main.home') }}">Home</a></div>
        <div class="element" id="search"><img src="{{ url_for('static', filename='search.png') }}" alt="search"><a href="{{ url_for('main.search') }}">Search</a></div>
      </div>

    <!-- Content -->
<div class="comment1">
    <div class="contentpic">
        <img src="{{ url_for('main.uploaded_file', filename=question.cover) }}" alt="Content Picture">
    </div>
    <span class="usericon"><img src="{{ url_for('static', filename='usericon.png') }}" alt=""></span>
    <span class="usernameComment">{{ question.user_id }}</span> 
    <span class="lastreply">Posted at {{ question.post_time }}</span>
    
    <span id="title">{{ question.title }}</span> 
    <span id="summary">{{ question.content }}</span> 
    <div class="answer1">
        <div class="answer1">
            <form action="/questionDetails_v1.html" method="post" enctype="multipart/form-data">
                <input type="hidden" name="question_id" value="{{ question.id }}">
                <input type="text" id="write" name="answer" placeholder="Write my answer">
                <input type="file" name="file" accept="image/*">
                <button type="submit" id="button-send">Send</button>
            </form>
        </div>
    </div>
</div>

    
<!-- Display answers -->
<div class="post2">
    {% for answer in answers %}
    <div class="answer-block">
        <span class="usernameAnswer2">{{ answer.id }}</span>
        <br><span class="lastAnswer2">Answered at {{ answer.answer_time }}</span>
        <!-- Assuming there's no image in 'Answer' model, so removing the image part -->
        <p>{{ answer.comment }}</p> <!-- Use 'comment' instead of 'text' -->
    </div>
    {% endfor %}
</div>

<!--  profile -->
<div class="profilemenu">
    <button id="authButton" type="button" class="button-profile" onclick="toggleAuth()">Sign up / Login</button>
    <button id="logoutButton" type="button" class="button-logout" onclick="logout()">Logout</button>
    <button id="addQuestion" type="button" class="button-addQuestion" onclick="location.href='{{ url_for('main.add_question') }}'">Add Question</button>
    <span class="userpic"><img src="../static/userpic.png" alt="userpic"></span>
    <span id="username" class="username"></span>
</div>

<!-- Login Modal -->
<div id="loginModal" class="login-modal">
    <h2>Login</h2>
    <input type="text" id="usernameInput" placeholder="Username"><br>
    <input type="password" id="passwordInput" placeholder="Password"><br>
    <button onclick="login()">Login</button>
    <button onclick="navigateToProfile()">Sign Up</button>
    <button onclick="closeModal()">Close</button>

</div>

<!-- Alert Modal -->
<div id="alertModal" class="alert-modal">
    <p id="alertMessage"></p>
</div>


<script src="{{ url_for('static', filename='scripts_qd.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

intelliShare/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IntelliShare</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../static/style.css">
</head>
<body>

   <!--  menu bar -->
   <div id="container">
    <span class="title">
        IntelliShare
    </span>
</div>
  
  <div class="menubar">
    <div class="element" id="home"><img src="{{ url_for('static', filename='home.png') }}" alt="home"><a href="{{ url_for('main.home') }}">Home</a></div>
    <div class="element" id="search"><img src="{{ url_for('static', filename='search.png') }}" alt="search"><a href="{{ url_for('main.search') }}">Search</a></div>
  </div>

<!-- Content -->

<!-- search-->
<div class="search-container">
  <form method="GET" action="/search">
      <input type="text" id="query" name="query" placeholder="Find a question, or answer">
      <button type="submit">Search</button>
  </form>

  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}

  {% endwith %}
  {% for result in results %}
  <h2><a href="{{ url_for('main.question_details_copy', question_id=result.id) }}">{{ result.title }}</a></h2>
  <p>{{ result.content }}</p>
{% endfor %}
</div>

<!--  profile -->
<div class="profilemenu">
    <button id="authButton" type="button" class="button-profile" onclick="toggleAuth()">Sign up / Login</button>
    <button id="logoutButton" type="button" class="button-logout" onclick="logout()">Logout</button>
    <button type="button" class="button-addQuestion" onclick="location.href='/addQuestion'">Add Question</button>
    <span class="userpic"><img src="{{ url_for('static', filename='userpic.png') }}" alt="userpic"></span>
    <span id="username" class="username"></span>
    
</div>


<!-- Login Modal -->
<div id="loginModal" class="login-modal">
  <h2>Login</h2>
  <input type="text" id="usernameInput" placeholder="Username"><br>
  <input type="password" id="passwordInput" placeholder="Password"><br>
  <button onclick="login()">Login</button>
  <button onclick="navigateToProfile()">Sign Up</button>
  <button onclick="closeModal()">Close</button>

</div>

<!-- Alert Modal -->
<div id="alertModal" class="alert-modal">
  <p id="alertMessage"></p>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='scripts_q1.js') }}"></script>
</body>
</html>